name: first_app
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.15.0  # Replace with the latest compatible version
  cloud_firestore: ^4.8.4  # Downgraded to resolve conflict
  firebase_auth: 4.7.0  # Compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
